"""
BDT configuration for hp_043 model.

Generated by hyperparameter exploration script.
Base config: 26Mar26_optimized
"""

from __future__ import annotations

CONFIG = {
    "modelname": "hp_043",
    "signals": ["ggfbbtt", "vbfbbtt-k2v0"],
    "n_folds": 5,
    "hyperpars": {
        "objective": "multi:softprob",
        "max_depth": 8,
        "eta": 0.13829199906021,
        "subsample": 0.641831013562353,
        "alpha": 2.301850388934091,
        "gamma": 1.3189602120761705,
        "lambda": 1.4182843097990139,
        "colsample_bytree": 0.6111921805318982,
        "num_parallel_tree": 28,
        "eval_metric": "mlogloss",
        "tree_method": "hist",
        "num_class": 11,
        "device": "cuda",
    },
    "num_rounds": 5000,
    "test_size": 0.2,
    "random_seed": 42,
    "var_classes": ["fatjet", "VBFJets", "leptons", "misc"],
    "train_vars": {
        "fatjet": [
            "ttFatJetPt",
            "ttFatJetPhi",
            "ttFatJetEta",
            "ttFatJetCAglobalParT_massVisApplied",
            "ttFatJetParTXtauhtauhvsQCDTop",
            "ttFatJetParTXtauhtauevsQCDTop",
            "ttFatJetParTXtauhtaumvsQCDTop",
            "ttFatJetTau3OverTau2",
        ],
        "VBFJets": ["VBFJetDeltaEta", "VBFMassjj"],
        "leptons": [
            "ttElectronPt",
            "ttElectronDeltaEta",
            "ttElectronDeltaPhi",
            "ttElectron_dRak8Jet",
            "ttElectronMass",
            "ttElectroncharge",
            "ttMuonPt",
            "ttMuonDeltaEta",
            "ttMuonDeltaPhi",
            "ttMuon_dRak8Jet",
            "ttMuonMass",
            "ttMuoncharge",
        ],
        "away": ["ttJetAwayPt", "ttJetAwayPhi", "ttJetAwayEta", "ttJetAwayMass"],
        "misc": ["METPt", "METPhi", "ht", "METsignificance"],
    },
}
