"""
BDT configuration for hp_083 model.

Generated by hyperparameter exploration script.
Base config: 26Mar26_optimized
"""

from __future__ import annotations

CONFIG = {
    "modelname": "hp_083",
    "signals": ["ggfbbtt", "vbfbbtt-k2v0"],
    "n_folds": 5,
    "hyperpars": {
        "objective": "multi:softprob",
        "max_depth": 9,
        "eta": 0.09169073944421677,
        "subsample": 0.6548193594982337,
        "alpha": 2.3501049097022664,
        "gamma": 3.956558284312723,
        "lambda": 3.3761834783943905,
        "colsample_bytree": 0.5858091797967565,
        "num_parallel_tree": 25,
        "eval_metric": "mlogloss",
        "tree_method": "hist",
        "num_class": 11,
        "device": "cuda",
    },
    "num_rounds": 5000,
    "test_size": 0.2,
    "random_seed": 42,
    "var_classes": ["fatjet", "VBFJets", "leptons", "misc"],
    "train_vars": {
        "fatjet": [
            "ttFatJetPt",
            "ttFatJetPhi",
            "ttFatJetEta",
            "ttFatJetCAglobalParT_massVisApplied",
            "ttFatJetParTXtauhtauhvsQCDTop",
            "ttFatJetParTXtauhtauevsQCDTop",
            "ttFatJetParTXtauhtaumvsQCDTop",
            "ttFatJetTau3OverTau2",
        ],
        "VBFJets": ["VBFJetDeltaEta", "VBFMassjj"],
        "leptons": [
            "ttElectronPt",
            "ttElectronDeltaEta",
            "ttElectronDeltaPhi",
            "ttElectron_dRak8Jet",
            "ttElectronMass",
            "ttElectroncharge",
            "ttMuonPt",
            "ttMuonDeltaEta",
            "ttMuonDeltaPhi",
            "ttMuon_dRak8Jet",
            "ttMuonMass",
            "ttMuoncharge",
        ],
        "away": ["ttJetAwayPt", "ttJetAwayPhi", "ttJetAwayEta", "ttJetAwayMass"],
        "misc": ["METPt", "METPhi", "ht", "METsignificance"],
    },
}
