"""
BDT configuration for hp_075 model.

Generated by hyperparameter exploration script.
Base config: 26Mar26_optimized
"""

from __future__ import annotations

CONFIG = {
    "modelname": "hp_075",
    "signals": ["ggfbbtt", "vbfbbtt-k2v0"],
    "n_folds": 5,
    "hyperpars": {
        "objective": "multi:softprob",
        "max_depth": 8,
        "eta": 0.1250810659659096,
        "subsample": 0.539985371087414,
        "alpha": 4.611480360211883,
        "gamma": 3.5608187323605858,
        "lambda": 1.3270839030653878,
        "colsample_bytree": 0.7181659336801975,
        "num_parallel_tree": 29,
        "eval_metric": "mlogloss",
        "tree_method": "hist",
        "num_class": 11,
        "device": "cuda",
    },
    "num_rounds": 5000,
    "test_size": 0.2,
    "random_seed": 42,
    "var_classes": ["fatjet", "VBFJets", "leptons", "misc"],
    "train_vars": {
        "fatjet": [
            "ttFatJetPt",
            "ttFatJetPhi",
            "ttFatJetEta",
            "ttFatJetCAglobalParT_massVisApplied",
            "ttFatJetParTXtauhtauhvsQCDTop",
            "ttFatJetParTXtauhtauevsQCDTop",
            "ttFatJetParTXtauhtaumvsQCDTop",
            "ttFatJetTau3OverTau2",
        ],
        "VBFJets": ["VBFJetDeltaEta", "VBFMassjj"],
        "leptons": [
            "ttElectronPt",
            "ttElectronDeltaEta",
            "ttElectronDeltaPhi",
            "ttElectron_dRak8Jet",
            "ttElectronMass",
            "ttElectroncharge",
            "ttMuonPt",
            "ttMuonDeltaEta",
            "ttMuonDeltaPhi",
            "ttMuon_dRak8Jet",
            "ttMuonMass",
            "ttMuoncharge",
        ],
        "away": ["ttJetAwayPt", "ttJetAwayPhi", "ttJetAwayEta", "ttJetAwayMass"],
        "misc": ["METPt", "METPhi", "ht", "METsignificance"],
    },
}
