"""
Intelligent hyperparameter exploration for BDT training.

This script generates BDT configuration files by systematically exploring
the hyperparameter space using Latin Hypercube Sampling (LHS) for efficient
coverage of the parameter space.

Authors: Generated for bbtautau project
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
from scipy.stats import qmc


def load_reference_config(config_path: Path) -> dict[str, Any]:
    """Load a reference configuration file to use as a base."""
    import importlib.util

    spec = importlib.util.spec_from_file_location("config", config_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.CONFIG.copy()


def generate_lhs_samples(
    n_samples: int,
    param_ranges: dict[str, tuple[float, float]],
    seed: int = 42,
) -> list[dict[str, float]]:
    """
    Generate Latin Hypercube Samples (LHS) for hyperparameter exploration.

    LHS ensures good coverage of the parameter space with fewer samples
    compared to random sampling or full grid search.

    Args:
        n_samples: Number of configurations to generate
        param_ranges: Dictionary mapping parameter names to (min, max) tuples
        seed: Random seed for reproducibility

    Returns:
        List of dictionaries with sampled parameter values
    """
    param_names = list(param_ranges.keys())
    n_params = len(param_names)

    # Generate LHS samples in [0, 1] space
    sampler = qmc.LatinHypercube(d=n_params, seed=seed)
    samples = sampler.random(n=n_samples)

    # Scale to actual parameter ranges
    configs = []
    for sample in samples:
        config = {}
        for i, param_name in enumerate(param_names):
            min_val, max_val = param_ranges[param_name]
            # For integer parameters, we'll round later
            config[param_name] = sample[i] * (max_val - min_val) + min_val
        configs.append(config)

    return configs


def round_integer_params(config: dict[str, float], int_params: list[str]) -> dict[str, Any]:
    """Round specified parameters to integers."""
    rounded = config.copy()
    for param in int_params:
        if param in rounded:
            rounded[param] = int(round(rounded[param]))
    return rounded


def generate_config_file(
    config: dict[str, Any],
    modelname: str,
    base_config: dict[str, Any],
    output_dir: Path,
) -> Path:
    """
    Generate a BDT configuration file from hyperparameters.

    Args:
        config: Dictionary of hyperparameter values
        modelname: Name for this model configuration
        base_config: Base configuration to inherit structure from
        output_dir: Directory to save the config file

    Returns:
        Path to the generated config file
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Create new config based on base
    new_config = base_config.copy()
    new_config["modelname"] = modelname

    # Update hyperparameters
    new_config["hyperpars"] = base_config["hyperpars"].copy()
    for param, value in config.items():
        if param in new_config["hyperpars"]:
            new_config["hyperpars"][param] = value

    # Generate Python file content with proper formatting
    # Use pprint-like formatting but match the style of existing configs
    import pprint

    pp = pprint.PrettyPrinter(indent=4, width=100, sort_dicts=False)
    config_repr = pp.pformat(new_config)

    config_str = f'''"""
BDT configuration for {modelname} model.

Generated by hyperparameter exploration script.
Base config: {base_config.get("modelname", "unknown")}
"""

CONFIG = {config_repr}
'''

    # Write config file
    config_file = output_dir / f"config_{modelname}.py"
    with config_file.open("w") as f:
        f.write(config_str)

    return config_file


_BDT_CONFIGS_DIR = Path(__file__).parent.parent / "postprocessing" / "bdt_configs"


def _resolve_base_config(raw_path: str) -> Path:
    """Resolve a base config path: accept absolute, relative, or bare filename.

    Search order:
      1. As given (absolute or relative to cwd)
      2. Under bdt_configs/ (recursive)
    """
    p = Path(raw_path)
    if p.exists():
        return p.resolve()
    # Bare filename or relative — search bdt_configs tree
    for candidate in _BDT_CONFIGS_DIR.rglob(p.name):
        return candidate.resolve()
    raise FileNotFoundError(
        f"Base config not found: tried '{raw_path}' and searched {_BDT_CONFIGS_DIR}"
    )


def main():
    parser = argparse.ArgumentParser(
        description="Generate BDT configuration files for hyperparameter exploration"
    )
    parser.add_argument(
        "--base-config",
        type=str,
        required=True,
        help="Path to base configuration file (e.g., config_11Feb26Full.py). "
        "Can be absolute, relative, or a bare filename (searched in bdt_configs/).",
    )
    parser.add_argument(
        "--group",
        type=str,
        required=True,
        help="Subfolder name inside postprocessing/bdt_configs/ to write configs into "
        "(e.g. 'key_pars_k2v0'). Created if it doesn't exist.",
    )
    parser.add_argument(
        "--n-configs",
        type=int,
        default=20,
        help="Number of configurations to generate (default: 20)",
    )
    parser.add_argument(
        "--prefix",
        type=str,
        default="hp",
        help="Prefix for generated model names (default: hp)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility (default: 42)",
    )
    parser.add_argument(
        "--strategy",
        type=str,
        choices=["lhs", "grid", "random"],
        default="lhs",
        help="Search strategy: lhs (Latin Hypercube), grid, or random (default: lhs)",
    )
    parser.add_argument(
        "--explore-all",
        action="store_true",
        help="Explore all hyperparameters. If False, only explores key parameters.",
    )

    args = parser.parse_args()

    # Resolve base configuration
    base_config_path = _resolve_base_config(args.base_config)
    base_config = load_reference_config(base_config_path)
    print(f"Loaded base config: {base_config['modelname']} ({base_config_path})")

    # Output goes directly into postprocessing/bdt_configs/<group>/
    output_dir = _BDT_CONFIGS_DIR / args.group

    # Define hyperparameter search ranges
    if args.explore_all:
        param_ranges = {
            "max_depth": (6, 14),
            "eta": (0.03, 0.15),
            "subsample": (0.2, 0.8),
            "colsample_bytree": (0.4, 1.0),
            "num_parallel_tree": (30, 70),
            "alpha": (0.5, 2.0),
            "gamma": (0.5, 2.0),
            "lambda": (0.5, 2.0),
        }
        int_params = ["max_depth", "num_parallel_tree"]
    else:
        param_ranges = {
            "max_depth": (6, 10),
            "eta": (0.05, 0.1),
            "subsample": (0.2, 0.6),
            "colsample_bytree": (0.5, 0.8),
            "num_parallel_tree": (1, 30),
        }
        int_params = ["max_depth", "num_parallel_tree"]

    # Generate configurations
    if args.strategy == "lhs":
        configs = generate_lhs_samples(args.n_configs, param_ranges, seed=args.seed)
    elif args.strategy == "grid":
        raise NotImplementedError("Grid search not yet implemented. Use --strategy lhs")
    else:  # random
        rng = np.random.default_rng(args.seed)
        configs = []
        for _ in range(args.n_configs):
            config = {}
            for param, (min_val, max_val) in param_ranges.items():
                config[param] = rng.uniform(min_val, max_val)
            configs.append(config)

    for i, config in enumerate(configs):
        configs[i] = round_integer_params(config, int_params)

    # Generate config files directly in postprocessing/bdt_configs/<group>/
    generated_files = []
    modelnames = []

    print(
        f"\nGenerating {len(configs)} configs in {output_dir.relative_to(_BDT_CONFIGS_DIR.parent.parent)}"
    )
    print(f"Strategy: {args.strategy}")
    print(f"Parameters explored: {list(param_ranges.keys())}\n")

    for i, config in enumerate(configs):
        modelname = f"{args.prefix}_{i+1:03d}"
        config_file = generate_config_file(config, modelname, base_config, output_dir)
        generated_files.append(config_file)
        modelnames.append(modelname)

        print(f"  {config_file.name}")
        print(
            f"    {', '.join(f'{k}={v:.3f}' if isinstance(v, float) else f'{k}={v}' for k, v in config.items())}"
        )

    # Save summary (used by generate_hp_jobs.py)
    summary = {
        "base_config": str(base_config_path),
        "group": args.group,
        "n_configs": len(configs),
        "strategy": args.strategy,
        "seed": args.seed,
        "param_ranges": {k: list(v) for k, v in param_ranges.items()},
        "modelnames": modelnames,
        "generated_files": [str(f) for f in generated_files],
    }

    summary_file = output_dir / "hp_exploration_summary.json"
    with summary_file.open("w") as f:
        json.dump(summary, f, indent=2)

    print(f"\nSummary saved to: {summary_file}")
    print(f"Total configurations generated: {len(generated_files)}")
    print("Configs are ready to use — no manual copying needed.")


if __name__ == "__main__":
    main()
