"""
BDT configuration for hp_086 model.

Generated by hyperparameter exploration script.
Base config: Apr30_19octUpd_ggf
"""

from __future__ import annotations

CONFIG = {
    "modelname": "hp_086",
    "signals": ["ggfbbtt"],
    "n_folds": 4,
    "hyperpars": {
        "objective": "multi:softprob",
        "max_depth": 7,
        "eta": 0.11905861467361786,
        "subsample": 0.5359646624380001,
        "alpha": 3.904551839192949,
        "gamma": 3.1360828202822626,
        "lambda": 3.4268355827219943,
        "colsample_bytree": 0.7386401602504995,
        "num_parallel_tree": 28,
        "eval_metric": "mlogloss",
        "tree_method": "hist",
        "num_class": 8,
        "device": "cuda",
    },
    "num_rounds": 1000,
    "test_size": 0.2,
    "random_seed": 42,
    "train_vars": {
        "fatjet": [
            "ttFatJetPt",
            "ttFatJetPhi",
            "ttFatJetEta",
            "ttFatJetParTmassResApplied",
            "ttFatJetCAglobalParT_massVisApplied",
            "ttFatJetParTmassVisApplied",
            "ttFatJetParTXtauhtauhvsQCDTop",
            "ttFatJetParTXtauhtauevsQCDTop",
            "ttFatJetParTXtauhtaumvsQCDTop",
            "ttFatJetTau3OverTau2",
        ],
        "VBFJets": ["VBFJetDeltaEta", "VBFMassjj"],
        "leptons": [
            "ttElectronPt",
            "ttElectronDeltaEta",
            "ttElectronDeltaPhi",
            "ttElectron_dRak8Jet",
            "ttElectronMass",
            "ttElectroncharge",
            "ttMuonPt",
            "ttMuonDeltaEta",
            "ttMuonDeltaPhi",
            "ttMuon_dRak8Jet",
            "ttMuonMass",
            "ttMuoncharge",
        ],
        "away": ["ttJetAwayPt", "ttJetAwayPhi", "ttJetAwayEta", "ttJetAwayMass"],
        "misc": ["METPt", "METPhi", "ht", "METsignificance"],
    },
}
