"""
BDT configuration for hp_025 model.

Generated by hyperparameter exploration script.
Base config: Apr30_19octUpd_ggf
"""

from __future__ import annotations

CONFIG = {
    "modelname": "hp_025",
    "signals": ["ggfbbtt"],
    "n_folds": 4,
    "hyperpars": {
        "objective": "multi:softprob",
        "max_depth": 7,
        "eta": 0.10671822112951257,
        "subsample": 0.549693431366751,
        "alpha": 4.555644708162314,
        "gamma": 2.516160440042844,
        "lambda": 3.9960354347194955,
        "colsample_bytree": 0.5204621950755268,
        "num_parallel_tree": 23,
        "eval_metric": "mlogloss",
        "tree_method": "hist",
        "num_class": 8,
        "device": "cuda",
    },
    "num_rounds": 1000,
    "test_size": 0.2,
    "random_seed": 42,
    "train_vars": {
        "fatjet": [
            "ttFatJetPt",
            "ttFatJetPhi",
            "ttFatJetEta",
            "ttFatJetParTmassResApplied",
            "ttFatJetCAglobalParT_massVisApplied",
            "ttFatJetParTmassVisApplied",
            "ttFatJetParTXtauhtauhvsQCDTop",
            "ttFatJetParTXtauhtauevsQCDTop",
            "ttFatJetParTXtauhtaumvsQCDTop",
            "ttFatJetTau3OverTau2",
        ],
        "VBFJets": ["VBFJetDeltaEta", "VBFMassjj"],
        "leptons": [
            "ttElectronPt",
            "ttElectronDeltaEta",
            "ttElectronDeltaPhi",
            "ttElectron_dRak8Jet",
            "ttElectronMass",
            "ttElectroncharge",
            "ttMuonPt",
            "ttMuonDeltaEta",
            "ttMuonDeltaPhi",
            "ttMuon_dRak8Jet",
            "ttMuonMass",
            "ttMuoncharge",
        ],
        "away": ["ttJetAwayPt", "ttJetAwayPhi", "ttJetAwayEta", "ttJetAwayMass"],
        "misc": ["METPt", "METPhi", "ht", "METsignificance"],
    },
}
