"""
BDT configuration for hp_016 model.

Generated by hyperparameter exploration script.
Base config: Apr30_19octUpd_ggf
"""

from __future__ import annotations

CONFIG = {
    "modelname": "hp_016",
    "signals": ["ggfbbtt"],
    "n_folds": 4,
    "hyperpars": {
        "objective": "multi:softprob",
        "max_depth": 8,
        "eta": 0.10474510737891163,
        "subsample": 0.6018311113577202,
        "alpha": 2.7727704131339967,
        "gamma": 0.8901562454450247,
        "lambda": 2.4734964115010283,
        "colsample_bytree": 0.7357525777934881,
        "num_parallel_tree": 21,
        "eval_metric": "mlogloss",
        "tree_method": "hist",
        "num_class": 8,
        "device": "cuda",
    },
    "num_rounds": 1000,
    "test_size": 0.2,
    "random_seed": 42,
    "train_vars": {
        "fatjet": [
            "ttFatJetPt",
            "ttFatJetPhi",
            "ttFatJetEta",
            "ttFatJetParTmassResApplied",
            "ttFatJetCAglobalParT_massVisApplied",
            "ttFatJetParTmassVisApplied",
            "ttFatJetParTXtauhtauhvsQCDTop",
            "ttFatJetParTXtauhtauevsQCDTop",
            "ttFatJetParTXtauhtaumvsQCDTop",
            "ttFatJetTau3OverTau2",
        ],
        "VBFJets": ["VBFJetDeltaEta", "VBFMassjj"],
        "leptons": [
            "ttElectronPt",
            "ttElectronDeltaEta",
            "ttElectronDeltaPhi",
            "ttElectron_dRak8Jet",
            "ttElectronMass",
            "ttElectroncharge",
            "ttMuonPt",
            "ttMuonDeltaEta",
            "ttMuonDeltaPhi",
            "ttMuon_dRak8Jet",
            "ttMuonMass",
            "ttMuoncharge",
        ],
        "away": ["ttJetAwayPt", "ttJetAwayPhi", "ttJetAwayEta", "ttJetAwayMass"],
        "misc": ["METPt", "METPhi", "ht", "METsignificance"],
    },
}
