"""
BDT configuration for 3Apr26_prod model.

Generated by hyperparameter exploration script.
Base config: 26Mar26_optimized
"""

from __future__ import annotations

CONFIG = {
    "modelname": "16Apr26_noreg",
    "signals": ["ggfbbtt", "vbfbbtt-k2v0"],
    "n_folds": 5,
    "hyperpars": {
        "objective": "multi:softprob",
        "max_depth": 11,
        "eta": 0.06,
        "subsample": 0.6,
        "alpha": 1.0,
        "gamma": 1.0,
        "lambda": 1.0,
        "colsample_bytree": 0.8,
        #  'num_parallel_tree': 1,
        "eval_metric": "mlogloss",
        "tree_method": "hist",
        "num_class": 11,
        "device": "cuda",
    },
    "num_rounds": 5000,
    "test_size": 0.2,
    "random_seed": 42,
    "var_classes": ["fatjet", "VBFJets", "leptons", "away", "misc"],
    "train_vars": {
        "fatjet": [
            "ttFatJetPt",
            "ttFatJetPhi",
            "ttFatJetEta",
            "ttFatJetCAglobalParT_massVisApplied",
            "ttFatJetParTXtauhtauhvsQCDTop",
            "ttFatJetParTXtauhtauevsQCDTop",
            "ttFatJetParTXtauhtaumvsQCDTop",
            "ttFatJetTau3OverTau2",
        ],
        "VBFJets": ["VBFJetDeltaEta", "VBFMassjj"],
        "leptons": [
            "ttElectronPt",
            #  'ttElectronDeltaEta',
            #  'ttElectronDeltaPhi',
            "ttElectron_dRak8Jet",
            "ttElectronMass",
            #  'ttElectroncharge',
            "ttMuonPt",
            #  'ttMuonDeltaEta',
            #  'ttMuonDeltaPhi',
            "ttMuon_dRak8Jet",
            "ttMuonMass",
            #  'ttMuoncharge'
        ],
        "away": ["ttJetAwayPt", "ttJetAwayPhi", "ttJetAwayEta", "ttJetAwayMass"],
        "misc": ["METPt", "METPhi", "ht", "METsignificance"],
    },
}
