from __future__ import annotations

"""
BDT Configuration Dictionary

Each model configuration must specify:
- signals: List of signal keys to use for training (1 or 2 elements)
    - 1 signal (e.g., ["ggfbbtt"]): 8 classes (3 signal channels + 5 backgrounds)
        - Class order: [signal_he, signal_hh, signal_hm, dyjets, qcd, ttbarhad, ttbarll, ttbarsl]
    - 2 signals (e.g., ["ggfbbtt", "vbfbbtt"]): 11 classes (3 ggf + 3 vbf + 5 backgrounds)
        - Class order: [ggfbbtthe, ggfbbtthh, ggfbbtthm, vbfbbtthe, vbfbbtthh, vbfbbtthm, dyjets, qcd, ttbarhad, ttbarll, ttbarsl]
- hyperpars.num_class: Must match the number of classes (8 for single signal, 11 for unified)
"""

BDT_CONFIG = {
    "28May25_baseline": {
        "modelname": "28May25_baseline",
        "signals": ["ggfbbtt"],  # Signal(s) to use for training
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 9,
            "subsample": 0.3,
            "alpha": 8.0,
            "gamma": 2.0,
            "lambda": 2.0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 100,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 30,
        "test_size": 0.8,
        "random_seed": 42,
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
                "ttFatJetParTXbb",
            ],
            "misc": ["METPt", "METPhi"],
        },
    },
    "test": {
        "modelname": "test",
        "signals": ["ggfbbtt"],
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "subsample": 0.3,
            "alpha": 8.0,
            "gamma": 2.0,
            "lambda": 2.0,
            "min_child_weight": 0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 10,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 10,
        "test_size": 0.8,
        "random_seed": 42,
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
                "ttFatJetParTXbb",
            ],
            "misc": ["METPt", "METPhi"],
        },
    },
    "10July25_baseline": {
        "modelname": "10July25_baseline",
        "signals": ["ggfbbtt"],
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 9,
            "subsample": 0.3,
            "alpha": 8.0,
            "gamma": 2.0,
            "lambda": 2.0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 100,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 30,
        "test_size": 0.8,
        "random_seed": 42,
        "train_vars": {
            "misc": ["METPt", "METPhi"],
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
                "ttFatJetParTXbb",
            ],
        },
    },
    "10July25_leptons": {
        "modelname": "10July25_leptons",
        "signals": ["ggfbbtt"],
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "subsample": 0.2,
            "alpha": 8.0,
            "gamma": 4.0,
            "lambda": 4.0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 70,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 50,
        "test_size": 0.2,
        "random_seed": 42,
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
                "ttFatJetParTXbb",
            ],
            "leptons": [
                "ttElectronPt",
                "ttElectronEta",
                "ttElectronPhi",
                "ttElectronMass",
                "ttMuonPt",
                "ttMuonEta",
                "ttMuonPhi",
                "ttMuonMass",
            ],
            "misc": ["METPt", "METPhi", "ht"],
        },
    },
    "13July25_leptons_noXbb": {
        "modelname": "13July25_leptons_noXbb",
        "signals": ["ggfbbtt"],
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "subsample": 0.2,
            "alpha": 8.0,
            "gamma": 4.0,
            "lambda": 4.0,
            "colsample_bytree": 1.0,
            "num_parallel_tree": 70,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 50,
        "test_size": 0.2,
        "random_seed": 42,
        "var_classes": ["fatjet", "leptons", "misc"],
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
            ],
            "leptons": [
                "ttElectronPt",
                "ttElectronEta",
                "ttElectronPhi",
                "ttElectronMass",
                "ttMuonPt",
                "ttMuonEta",
                "ttMuonPhi",
                "ttMuonMass",
            ],
            "misc": ["METPt", "METPhi", "ht"],
        },
    },
    "29July25_loweta_lowreg": {
        "modelname": "29July25_loweta_lowreg",
        "signals": ["ggfbbtt"],
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "eta": 0.07,
            "subsample": 0.2,
            "alpha": 1.0,
            "gamma": 1.0,
            "lambda": 1.0,
            "colsample_bytree": 0.6,
            "num_parallel_tree": 20,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            # "device": "cuda",
        },
        "num_rounds": 300,
        "test_size": 0.2,
        "random_seed": 42,
        "var_classes": ["fatjet", "leptons", "misc"],
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
            ],
            "leptons": [
                "ttElectronPt",
                "ttElectronEta",
                "ttElectronPhi",
                "ttElectronMass",
                "ttMuonPt",
                "ttMuonEta",
                "ttMuonPhi",
                "ttMuonMass",
            ],
            "misc": ["METPt", "METPhi", "ht"],
        },
    },
    "20aug25_loweta_lowreg": {
        "modelname": "20aug25_loweta_lowreg",
        "signals": ["ggfbbtt"],
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "eta": 0.07,
            "subsample": 0.2,
            "alpha": 1.0,
            "gamma": 1.0,
            "lambda": 1.0,
            "colsample_bytree": 0.6,
            "num_parallel_tree": 20,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            "device": "cuda",
        },
        "num_rounds": 100,
        "test_size": 0.2,
        "random_seed": 42,
        "var_classes": ["fatjet", "leptons", "misc"],
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
            ],
            "leptons": [
                "ttElectronPt",
                "ttElectronDeltaEta",
                "ttElectronDeltaPhi",
                "ttElectron_dRak8Jet",
                "ttElectronMass",
                "ttElectroncharge",
                "ttMuonPt",
                "ttMuonDeltaEta",
                "ttMuonDeltaPhi",
                "ttMuon_dRak8Jet",
                "ttMuonMass",
                "ttMuoncharge",
            ],
            "misc": ["METPt", "METPhi", "ht"],
        },
    },
    "20aug25_loweta_lowreg_vbf": {
        "modelname": "20aug25_loweta_lowreg_vbf",
        "signals": ["vbfbbtt"],  # VBF-only model
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "eta": 0.07,
            "subsample": 0.2,
            "alpha": 1.0,
            "gamma": 1.0,
            "lambda": 1.0,
            "colsample_bytree": 0.6,
            "num_parallel_tree": 20,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            "device": "cuda",
        },
        "num_rounds": 100,
        "test_size": 0.2,
        "random_seed": 42,
        "var_classes": ["fatjet", "leptons", "misc"],
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
            ],
            "leptons": [
                "ttElectronPt",
                "ttElectronDeltaEta",
                "ttElectronDeltaPhi",
                "ttElectron_dRak8Jet",
                "ttElectronMass",
                "ttElectroncharge",
                "ttMuonPt",
                "ttMuonDeltaEta",
                "ttMuonDeltaPhi",
                "ttMuon_dRak8Jet",
                "ttMuonMass",
                "ttMuoncharge",
            ],
            "misc": ["METPt", "METPhi", "ht"],
        },
    },
    "19oct25_ak4away_ggfbbtt": {
        "modelname": "19oct25_ak4away_ggfbbtt",
        "signals": ["ggfbbtt"],
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "eta": 0.07,
            "subsample": 0.2,
            "alpha": 1.0,
            "gamma": 1.0,
            "lambda": 1.0,
            "colsample_bytree": 0.6,
            "num_parallel_tree": 50,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            "device": "cuda",
        },
        "num_rounds": 100,
        "test_size": 0.2,
        "random_seed": 42,
        "var_classes": ["fatjet", "leptons", "misc"],
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
            ],
            "leptons": [
                "ttElectronPt",
                "ttElectronDeltaEta",
                "ttElectronDeltaPhi",
                "ttElectron_dRak8Jet",
                "ttElectronMass",
                "ttElectroncharge",
                "ttMuonPt",
                "ttMuonDeltaEta",
                "ttMuonDeltaPhi",
                "ttMuon_dRak8Jet",
                "ttMuonMass",
                "ttMuoncharge",
            ],
            "away": [
                "ttJetAwayPt",
                "ttJetAwayPhi",
                "ttJetAwayEta",
                "ttJetAwayMass",
            ],
            "misc": ["METPt", "METPhi", "ht"],
        },
    },
    "19oct25_ak4away_vbfbbtt": {
        "modelname": "19oct25_ak4away_vbfbbtt",
        "signals": ["vbfbbtt"],
        "hyperpars": {
            "objective": "multi:softprob",
            "max_depth": 12,
            "eta": 0.07,
            "subsample": 0.2,
            "alpha": 1.0,
            "gamma": 1.0,
            "lambda": 1.0,
            "colsample_bytree": 0.6,
            "num_parallel_tree": 50,
            "eval_metric": "mlogloss",
            "tree_method": "hist",
            "num_class": 8,
            "device": "cuda",
        },
        "num_rounds": 100,
        "test_size": 0.2,
        "random_seed": 42,
        "var_classes": ["fatjet", "leptons", "misc"],
        "train_vars": {
            "fatjet": [
                "ttFatJetPt",
                "ttFatJetPhi",
                "ttFatJetEta",
                "ttFatJetParTmassResApplied",
                "ttFatJetParTmassVisApplied",
                "ttFatJetParTQCD",
                "ttFatJetParTTop",
                "ttFatJetParTQCD0HF",
                "ttFatJetParTQCD1HF",
                "ttFatJetParTQCD2HF",
                "ttFatJetParTTopW",
                "ttFatJetParTTopbW",
                "ttFatJetParTXtauhtauh",
                "ttFatJetParTXtauhtaue",
                "ttFatJetParTXtauhtaum",
            ],
            "leptons": [
                "ttElectronPt",
                "ttElectronDeltaEta",
                "ttElectronDeltaPhi",
                "ttElectron_dRak8Jet",
                "ttElectronMass",
                "ttElectroncharge",
                "ttMuonPt",
                "ttMuonDeltaEta",
                "ttMuonDeltaPhi",
                "ttMuon_dRak8Jet",
                "ttMuonMass",
                "ttMuoncharge",
            ],
            "away": [
                "ttJetAwayPt",
                "ttJetAwayPhi",
                "ttJetAwayEta",
                "ttJetAwayMass",
            ],
            "misc": ["METPt", "METPhi", "ht"],
        },
    },
}
