apiVersion: batch/v1
kind: Job
metadata:
  name: bbtautau-bdt-$job_name
  labels:
    type: bbtautau
spec:
  template:
    spec:
      containers:
      - name: bbtautau
        image: gitlab-registry.nrp-nautilus.io/ludomori99/bbtautau-docker:latest
        command:
          - "/bin/bash"
          - "-c"
          - >
            git clone --single-branch --recurse-submodules --branch dev-bdt https://github.com/LPC-HH/bbtautau.git /opt/repo/bbtautau &&
            mkdir -p $output_dir/ &&
            pip install -e /opt/repo/bbtautau &&
            pip install -e /opt/repo/bbtautau/boostedhh &&
            python /opt/repo/bbtautau/src/bbtautau/postprocessing/bdt.py --years all --study-rescaling --model $modelname
            --output-dir $output_dir --data-path $datapath/ $args
            2>&1 | tee $output_dir/log.txt
        volumeMounts:
        - mountPath: /bbtautauvol
          name: bbtautauvol
        resources:
          limits:
            memory: ${memory}Gi
            cpu: "2.4"
            nvidia.com/gpu: "1"
          requests:
            memory: ${memory}Gi
            cpu: "2"
            nvidia.com/gpu: "1"
      volumes:
      - name: bbtautauvol
        persistentVolumeClaim:
          claimName: bbtautauvol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - service-02.nrp.mghpcc.org
                      - clu-fiona2.ucmerced.edu
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                    - NVIDIA-GeForce-RTX-4090
                    - NVIDIA-GeForce-RTX-3090
                    - NVIDIA-A10
                    - NVIDIA-TITAN-RTX
                    - NVIDIA-RTX-A5000
                    - Quadro-RTX-6000
                    - Tesla-V100-SXM2-32GB
      restartPolicy: Never
  backoffLimit: 0
